server:
  port: 8080
spring:
  application:
    name: backend.springboot-kotlin.elo
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2