version: "3.8"
services:
  mockServer:
    image: mockserver/mockserver:5.13.2
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: .
        target: /config
